/* =====================================================================
   BANQUE DE QUESTIONS — Jeu "Vous Deux"  (200 questions)
   ---------------------------------------------------------------------
   👉 POUR AJOUTER UNE QUESTION : copie-colle une ligne et modifie-la.
      Format :  { cat: "amour", q: "Ta question ?", o: ["Choix 1", "Choix 2", "Choix 3", "Choix 4"] },

   - "cat"  = la catégorie (amour | fun | profond | couple | coquin).
   - "q"    = la question, posée à la personne SUR ELLE-MÊME ("toi").
   - "o"    = les choix de réponse (3 ou 4).

   Le jeu pioche un mélange aléatoire à chaque partie → on rejoue sans
   retomber sur les mêmes questions.
   ===================================================================== */

const CATEGORIES = {
  amour:   { label: "Amour & couple", emoji: "💕", color: "#ff6b9d" },
  fun:     { label: "Fun & décalé",   emoji: "😂", color: "#ffb347" },
  profond: { label: "Profond & perso", emoji: "🧠", color: "#9d7bff" },
  couple:  { label: "Problématiques de couple", emoji: "🤔", color: "#4ecdc4" },
  coquin:  { label: "Coquin",         emoji: "🌶️", color: "#ff5252" },
};

const QUESTIONS = [
  /* ============== 💕 AMOUR & COUPLE ============== */
  { cat: "amour", q: "Ta façon préférée de recevoir de l'amour ?", o: ["Les câlins & le contact", "Les mots doux", "Les petites attentions", "Du temps rien qu'à deux"] },
  { cat: "amour", q: "Ton langage de l'amour n°1 ?", o: ["Le toucher physique", "Les compliments", "Les services rendus", "Le temps de qualité"] },
  { cat: "amour", q: "Le moment idéal d'une journée à deux ?", o: ["Le réveil collé-serré", "Un dîner aux chandelles", "Une soirée film canapé", "Une balade main dans la main"] },
  { cat: "amour", q: "Ce qui te fait le plus craquer chez l'autre ?", o: ["Son sourire", "Son humour", "Son intelligence", "Son popotin (avoue)"] },
  { cat: "amour", q: "Ton idée du rendez-vous parfait ?", o: ["Resto romantique", "Activité fun (escape game...)", "Soirée cocooning maison", "Sortie nature / rando"] },
  { cat: "amour", q: "Comment tu préfères dire 'je t'aime' ?", o: ["Avec des mots", "Avec des gestes", "Avec des surprises", "En offrant ma dernière frite"] },
  { cat: "amour", q: "Ton surnom secret pour l'autre, c'est plutôt ?", o: ["Un truc mignon (doudou)", "Un truc animalier (mon lapin)", "Un classique (bébé)", "Un truc absurde qu'on assume pas"] },
  { cat: "amour", q: "Le cadeau qui te toucherait le plus ?", o: ["Une surprise romantique", "Quelque chose d'utile", "Une expérience à vivre", "Un truc fait main"] },
  { cat: "amour", q: "Ta manière de te réconcilier après une dispute ?", o: ["Un gros câlin", "En parler calmement", "Faire rire l'autre", "Commander à manger"] },
  { cat: "amour", q: "Ce que tu admires le plus chez ton/ta partenaire ?", o: ["Sa force", "Sa gentillesse", "Sa créativité", "Sa capacité à dormir partout"] },
  { cat: "amour", q: "Le couple de fiction qui vous ressemble ?", o: ["Les romantiques classiques", "Le duo comique", "Les aventuriers", "Le vieux couple adorable"] },
  { cat: "amour", q: "Notre meilleur souvenir, c'est plutôt ?", o: ["Notre rencontre", "Notre 1er voyage", "Un énorme fou rire", "Un moment tout simple"] },
  { cat: "amour", q: "Si on était une chanson, ce serait ?", o: ["Une ballade romantique", "Un tube qui bouge", "Un slow un peu ringard", "Un truc complètement improbable"] },
  { cat: "amour", q: "Ce qui te manque le plus quand l'autre est absent ?", o: ["Sa présence", "Ses câlins", "Ses bêtises", "Quelqu'un pour finir mon assiette"] },
  { cat: "amour", q: "Ton geste d'amour au quotidien préféré ?", o: ["Un message mignon", "Préparer à manger", "Un câlin surprise", "Lui laisser toute la couette"] },
  { cat: "amour", q: "La 1re chose que tu as remarquée chez l'autre ?", o: ["Son regard", "Son sourire", "Sa voix", "Son style"] },
  { cat: "amour", q: "Ta date de couple idéale un soir de flemme ?", o: ["Pizza + série", "Jeu de société", "Bain à deux", "Chacun son téléphone, collés"] },
  { cat: "amour", q: "Comment tu réagis quand l'autre est malade ?", o: ["Infirmier(e) dévoué(e)", "Je panique grave", "Je garde mes distances", "Soupe + câlins illimités"] },
  { cat: "amour", q: "Ce que tu préfères faire ensemble le week-end ?", o: ["Sortir", "Glander à la maison", "Voir des amis", "Un projet / bricolage"] },
  { cat: "amour", q: "Ton niveau de jalousie, franchement ?", o: ["Zéro, jamais", "Un tout petit peu", "Modéré mais ça va", "Assumé à 200%"] },
  { cat: "amour", q: "Ta Saint-Valentin idéale ?", o: ["Grand restaurant", "Soirée maison", "Week-end surprise", "On s'en fiche un peu"] },
  { cat: "amour", q: "Le truc qui te fait fondre instantanément ?", o: ["Un compliment", "Un câlin par surprise", "Un petit mot", "Le petit-déj au lit"] },
  { cat: "amour", q: "Si l'autre te réveille à 3h pour un câlin, tu ?", o: ["J'adore", "Je grogne mais j'accepte", "Je dis non catégorique", "J'étais déjà réveillé(e)"] },
  { cat: "amour", q: "Ce que tu veux qu'on garde toujours ?", o: ["Les fous rires", "La complicité", "La passion", "Les bêtises"] },
  { cat: "amour", q: "Ta démonstration d'affection en public ?", o: ["Main dans la main", "Câlins partout", "Plutôt discret(e)", "Zéro devant les gens"] },
  { cat: "amour", q: "Quand l'autre rentre à la maison, tu ?", o: ["Je saute dans ses bras", "Un petit bisou", "Un coucou de loin", "Je continue ma série"] },
  { cat: "amour", q: "Le compliment qui te fait le plus plaisir ?", o: ["Sur ton physique", "Sur ton humour", "Sur ton intelligence", "Sur ta cuisine"] },
  { cat: "amour", q: "Ton plus grand romantisme assumé ?", o: ["Les bougies", "Les petits mots", "Les surprises", "Les playlists dédiées"] },
  { cat: "amour", q: "Si on gagnait au loto, ta 1re réaction ?", o: ["On voyage partout", "On achète une maison", "On démissionne demain", "On cache tout et on vit normal"] },
  { cat: "amour", q: "Ce que tu ferais pour l'autre sans hésiter ?", o: ["Traverser la ville à pied", "Manger un truc dégoûtant", "Affronter sa belle-famille", "Tout, je suis trop gentil(le)"] },
  { cat: "amour", q: "Ton idée d'un câlin parfait ?", o: ["Long et silencieux", "Plein de bisous", "Sous la couette", "Façon koala accroché"] },
  { cat: "amour", q: "La qualité que tu cherchais chez un(e) partenaire ?", o: ["L'humour", "La fidélité", "La douceur", "Quelqu'un qui me supporte"] },
  { cat: "amour", q: "Le moment où tu t'es dit 'c'est lui/elle' ?", o: ["Très vite", "Après quelques mois", "Petit à petit", "Toujours pas sûr(e) mdr"] },
  { cat: "amour", q: "Ta façon de montrer que tu tiens à l'autre ?", o: ["Je le dis", "Par des gestes", "Présent(e) dans les coups durs", "Je taquine sans arrêt"] },
  { cat: "amour", q: "Le voyage de rêve à deux ?", o: ["Plage paradisiaque", "Road trip aventure", "Grande ville", "Cabane dans la nature"] },
  { cat: "amour", q: "Ce que tu adores dans notre routine ?", o: ["Les repas ensemble", "Les soirées canap'", "Le réveil à deux", "Les courses (étonnamment)"] },
  { cat: "amour", q: "Si l'autre te fait une surprise, tu ?", o: ["J'adore les surprises", "Je suis super gêné(e)", "J'aurais préféré choisir", "Je devine toujours tout"] },
  { cat: "amour", q: "Ton mot doux préféré à entendre ?", o: ["Je t'aime", "Tu me manques", "Je suis fier(e) de toi", "T'es trop beau/belle"] },
  { cat: "amour", q: "La tradition de couple que tu préfères ?", o: ["Le ciné régulier", "Le resto du vendredi", "Le voyage annuel", "Le câlin du matin"] },
  { cat: "amour", q: "Au fond, ce qui te rend le plus heureux(se) ?", o: ["Me sentir aimé(e)", "Rire ensemble", "Construire des projets", "Juste être là à deux"] },

  /* ============== 😂 FUN & DÉCALÉ ============== */
  { cat: "fun", q: "En soirée, tu es plutôt ?", o: ["La star de la piste", "Le/la roi(ne) du bar", "Discret(e) dans un coin", "Le/la premier(e) à partir"] },
  { cat: "fun", q: "Si tu étais un animal, tu serais ?", o: ["Un chat indépendant", "Un chien fidèle", "Un paresseux", "Un renard malin"] },
  { cat: "fun", q: "Ton péché mignon le soir ?", o: ["Grignoter du sucré", "Du salé / chips", "Une série en boucle", "Scroller le téléphone"] },
  { cat: "fun", q: "Ta réaction quand tu es en retard ?", o: ["Je stresse à fond", "Je reste zen", "Je cours partout", "Je préviens 10 fois"] },
  { cat: "fun", q: "Le matin, tu es ?", o: ["Du matin, plein(e) d'énergie", "Grognon(ne) avant le café", "Snooze x10", "Ça dépend des jours"] },
  { cat: "fun", q: "Ton super-pouvoir de rêve ?", o: ["Voler", "Lire les pensées", "Être invisible", "Me téléporter direct au lit"] },
  { cat: "fun", q: "Sur une île déserte, tu emportes ?", o: ["Ton téléphone", "Un bon livre", "De la musique", "Du papier toilette (réaliste)"] },
  { cat: "fun", q: "Ta phobie la plus assumée ?", o: ["Les araignées", "Le vide", "Les espaces confinés", "Le dentiste"] },
  { cat: "fun", q: "Au resto, tu commandes toujours ?", o: ["Le même plat habituel", "Le truc le plus original", "Pareil que l'autre", "J'hésite 20 minutes"] },
  { cat: "fun", q: "Ton karaoké de prédilection ?", o: ["Une ballade émouvante", "Un tube qui bouge", "Un classique des années 80", "Jamais de karaoké pour moi"] },
  { cat: "fun", q: "Ta plus grande maladresse au quotidien ?", o: ["Je renverse tout", "Je me cogne partout", "J'oublie les noms", "Je perds mes affaires"] },
  { cat: "fun", q: "Ton comportement face à un buffet à volonté ?", o: ["Je teste absolument tout", "Je vise le meilleur", "Je me ressers 5 fois", "Je culpabilise mais j'y vais"] },
  { cat: "fun", q: "Quand tu rates une marche en public, tu ?", o: ["Je fais comme si de rien", "Je ris de moi-même", "Je vérifie si on m'a vu", "Je meurs de honte"] },
  { cat: "fun", q: "Ton niveau au ménage ?", o: ["Maniaque", "Correct", "Seulement quand y a de la visite", "Le chaos organisé"] },
  { cat: "fun", q: "Ta position de sommeil ?", o: ["En étoile", "En boule", "Sur le ventre", "Façon momie immobile"] },
  { cat: "fun", q: "Combien de temps pour te préparer ?", o: ["5 min chrono", "20 minutes", "45 minutes", "Ne me juge pas"] },
  { cat: "fun", q: "Ton dilemme du frigo ?", o: ["Je grignote tout", "Je regarde et je referme", "Je cuisine vraiment", "Je commande à la place"] },
  { cat: "fun", q: "Face à une araignée, tu ?", o: ["Je la tue", "Je la sors dehors", "J'appelle au secours", "Je quitte la pièce (voire le pays)"] },
  { cat: "fun", q: "Ton genre de film le vendredi soir ?", o: ["Comédie", "Action", "Romantique", "Documentaire pour s'endormir"] },
  { cat: "fun", q: "Ton talent caché complètement inutile ?", o: ["Les imitations", "Les bruitages", "Réciter des répliques", "Manger très vite"] },
  { cat: "fun", q: "Si tu étais un emoji, tu serais ?", o: ["😂", "😎", "🥺", "😴"] },
  { cat: "fun", q: "Ta réaction devant un chien dans la rue ?", o: ["Je fonce le caresser", "Je souris de loin", "Je l'évite poliment", "J'ai envie de le voler"] },
  { cat: "fun", q: "Comment tu manges une pizza ?", o: ["Avec les mains", "À la fourchette (criminel)", "Je plie la part", "La croûte d'abord"] },
  { cat: "fun", q: "Ton style de danse ?", o: ["Très à l'aise", "Les bras seulement", "Je fais semblant", "Réservé strictement au salon"] },
  { cat: "fun", q: "Ta réaction quand le wifi coupe ?", o: ["Panique totale", "Je redémarre la box", "Je râle fort", "Enfin un peu de calme"] },
  { cat: "fun", q: "Ton rapport à l'alarme du matin ?", o: ["Je me lève direct", "Snooze 1 fois", "Snooze à l'infini", "Je l'ai pas entendue"] },
  { cat: "fun", q: "Ton comportement en voiture ?", o: ["Pilote tranquille", "Je chante à tue-tête", "Je critique les autres", "Je m'endors (en passager)"] },
  { cat: "fun", q: "Ta nourriture réconfort ultime ?", o: ["Pâtes / fromage", "Chocolat", "Burger-frites", "Glace direct du pot"] },
  { cat: "fun", q: "Si tu étais un méchant de film ?", o: ["Le charismatique", "Le maladroit", "Le génie incompris", "Trop gentil pour être méchant"] },
  { cat: "fun", q: "Ton niveau de patience dans une file d'attente ?", o: ["Zen total", "Je soupire fort", "Je calcule la file la plus rapide", "Je pars carrément"] },
  { cat: "fun", q: "Ta réaction à une blague nulle ?", o: ["Je ris quand même", "Regard blasé", "Je ris jaune", "J'en refais une pire"] },
  { cat: "fun", q: "Le truc que tu googles le plus ?", o: ["Des recettes", "Trajets / météo", "Des questions existentielles à 2h", "Comment faire un truc débile"] },
  { cat: "fun", q: "Ton attitude le jour de ton anniversaire ?", o: ["J'organise tout", "J'aime qu'on s'occupe de moi", "Je veux rien faire", "Je le rappelle à tout le monde"] },
  { cat: "fun", q: "Quand quelqu'un pique dans ton assiette ?", o: ["Aucun souci", "Ça dépend qui", "Je grogne", "Touche pas à ma nourriture"] },
  { cat: "fun", q: "Ton talent en cuisine ?", o: ["Top chef", "Correct", "Les pâtes et c'est tout", "Je brûle l'eau"] },
  { cat: "fun", q: "Ton comportement quand tu es malade ?", o: ["Stoïque", "Je me plains beaucoup", "Mode bébé total", "Je nie être malade"] },
  { cat: "fun", q: "Ta réaction devant un film d'horreur ?", o: ["J'adore", "Je sursaute très fort", "Je cache mes yeux", "Je ris pour me rassurer"] },
  { cat: "fun", q: "Ton niveau de compétition en jeu de société ?", o: ["Pour s'amuser", "Un peu sérieux", "Je veux gagner", "Mauvais perdant assumé"] },
  { cat: "fun", q: "Si tu pouvais manger une seule chose à vie ?", o: ["Pizza", "Sushis", "Pâtes", "Chocolat"] },
  { cat: "fun", q: "Ta réaction quand on te fait un compliment ?", o: ["Merci tranquille", "Je rougis", "Je minimise", "Je retourne le compliment"] },
  { cat: "fun", q: "Ton rituel honteux mais assumé ?", o: ["Parler tout(e) seul(e)", "Chanter sous la douche", "Relire mes propres messages", "Sentir mes vêtements propres"] },
  { cat: "fun", q: "Ton attitude en photo ?", o: ["Naturel", "Toujours la même pose", "Je fais le clown", "Je déteste les photos"] },
  { cat: "fun", q: "Ta gestion d'un dimanche pluvieux ?", o: ["Marathon de séries", "Cuisine / pâtisserie", "Sieste géante", "Grand ménage"] },
  { cat: "fun", q: "Face à une notif non lue, tu ?", o: ["Je l'ouvre direct", "J'attends le bon moment", "Je laisse le badge rouge (monstre)", "J'oublie de répondre"] },
  { cat: "fun", q: "Si tu étais une saison ?", o: ["Été festif", "Hiver cocooning", "Printemps fleur bleue", "Automne mélancolique"] },
  { cat: "fun", q: "Quand le GPS te fait tromper de route, tu ?", o: ["Je recalcule calmement", "Je panique", "Je blâme le GPS", "Je fais comme si c'était voulu"] },
  { cat: "fun", q: "Ton niveau de coordination sportive ?", o: ["Athlète", "Correct", "Deux pieds gauches", "Le sport et moi, ça fait deux"] },
  { cat: "fun", q: "Avec une machine à voyager dans le temps, tu ?", o: ["Voir le futur", "Changer le passé", "Rencontrer une star", "Récupérer mon café d'il y a 2h"] },
  { cat: "fun", q: "Ta réaction si tu croises ton ex dans la rue ?", o: ["Coucou poli", "Je fais semblant de pas voir", "Demi-tour discret", "Aucun souci"] },
  { cat: "fun", q: "Ton attitude au réveil un jour férié ?", o: ["Debout à la même heure", "Grasse mat sacrée", "Je me rendors 3 fois", "Je culpabilise puis je dors"] },
  { cat: "fun", q: "Ton plus grand combat du quotidien ?", o: ["Le réveil", "Choisir quoi manger", "Répondre aux messages", "Plier le linge"] },
  { cat: "fun", q: "Si tu étais un objet de la maison ?", o: ["La télécommande", "Le canapé", "La cafetière", "La couette"] },
  { cat: "fun", q: "Ta réaction à une pub trop longue ?", o: ["J'attends sagement", "Je zappe", "Je skip dès que possible", "Je vais grignoter"] },
  { cat: "fun", q: "Ton type d'humour ?", o: ["Absurde", "Ironique / sarcastique", "Jeux de mots nuls", "Humour potache"] },
  { cat: "fun", q: "Ta gestion d'une plante verte ?", o: ["Elle prospère", "Elle survit", "Elle agonise", "RIP à toutes mes plantes"] },

  /* ============== 🧠 PROFOND & PERSO ============== */
  { cat: "profond", q: "Ce qui compte le plus pour toi dans la vie ?", o: ["La famille", "La liberté", "La réussite", "L'amour"] },
  { cat: "profond", q: "Ta plus grande peur ?", o: ["Être seul(e)", "L'échec", "Perdre un proche", "L'inconnu"] },
  { cat: "profond", q: "Comment tu te ressources vraiment ?", o: ["Seul(e) au calme", "Avec ceux que j'aime", "En faisant du sport", "En voyageant"] },
  { cat: "profond", q: "Dans 5 ans, tu te vois ?", o: ["En famille", "En train de voyager", "Focus carrière", "On verra bien"] },
  { cat: "profond", q: "Ce qui te rend le plus fier(e) de toi ?", o: ["Mon parcours", "Mes relations", "Ma personnalité", "Mes projets"] },
  { cat: "profond", q: "Ta source de motivation principale ?", o: ["Mes proches", "Mes rêves", "Me dépasser", "La peur de regretter"] },
  { cat: "profond", q: "Quand tu vas mal, tu as besoin de ?", o: ["Qu'on t'écoute", "Qu'on te laisse seul(e)", "Qu'on te change les idées", "Qu'on te fasse un câlin"] },
  { cat: "profond", q: "Ce que tu aimerais améliorer chez toi ?", o: ["Ma confiance en moi", "Ma patience", "Mon organisation", "Ma communication"] },
  { cat: "profond", q: "Le bonheur, pour toi, c'est surtout ?", o: ["Des petits moments simples", "Réaliser ses rêves", "Être bien entouré(e)", "La paix intérieure"] },
  { cat: "profond", q: "Tu te décrirais plutôt comme ?", o: ["Un(e) rêveur(se)", "Un(e) réaliste", "Un(e) fonceur(se)", "Un(e) sensible"] },
  { cat: "profond", q: "Ton rapport au risque ?", o: ["J'adore le risque", "Calculé", "Plutôt prudent(e)", "Zéro risque pour moi"] },
  { cat: "profond", q: "Ce que tu sauverais d'une maison en feu (après les gens) ?", o: ["Photos / souvenirs", "Le téléphone", "Un objet sentimental", "Mon animal"] },
  { cat: "profond", q: "Ta plus grande qualité selon toi ?", o: ["La loyauté", "L'empathie", "La détermination", "L'humour"] },
  { cat: "profond", q: "Ton plus gros défaut, assumé ?", o: ["Têtu(e)", "Impatient(e)", "Désordonné(e)", "Rancunier(e)"] },
  { cat: "profond", q: "Ce qui te donne le plus d'énergie ?", o: ["Les projets", "Les gens", "La nature", "Les défis"] },
  { cat: "profond", q: "Ce que tu regrettes de ne pas faire assez ?", o: ["Voyager", "Voir mes proches", "Prendre soin de moi", "Suivre mes rêves"] },
  { cat: "profond", q: "Ta définition de la réussite ?", o: ["Être heureux", "Être libre", "Avoir de la stabilité", "Avoir un impact"] },
  { cat: "profond", q: "Comment tu prends les critiques ?", o: ["Bien, j'apprends", "Ça me touche", "Je me braque", "Ça dépend de qui"] },
  { cat: "profond", q: "Ce que tu admires le plus chez les autres ?", o: ["Le courage", "La gentillesse", "L'intelligence", "La créativité"] },
  { cat: "profond", q: "Ton moteur dans la vie ?", o: ["L'amour", "La curiosité", "L'ambition", "La sérénité"] },
  { cat: "profond", q: "Si tu pouvais transmettre une seule valeur ?", o: ["Le respect", "La bienveillance", "La persévérance", "La liberté"] },
  { cat: "profond", q: "Ton rapport au changement ?", o: ["J'adore", "Ça me stresse mais je gère", "J'ai besoin de temps", "Je résiste"] },
  { cat: "profond", q: "Ce qui peut te faire pleurer ?", o: ["Les films / musiques", "Les retrouvailles", "La colère", "Presque rien"] },
  { cat: "profond", q: "Ce que tu fais quand tu es stressé(e) ?", o: ["Je m'isole", "Je parle", "Je fais du sport", "Je grignote"] },
  { cat: "profond", q: "Le compliment qui te toucherait le plus profondément ?", o: ["T'es quelqu'un de bien", "Je suis fier(e) de toi", "Tu m'inspires", "On peut compter sur toi"] },
  { cat: "profond", q: "Ton rêve un peu fou ?", o: ["Le tour du monde", "Vivre ailleurs", "Créer quelque chose", "Une vie tranquille"] },
  { cat: "profond", q: "Ce que tu préfères chez toi physiquement ?", o: ["Mes yeux", "Mon sourire", "Mes cheveux", "Euh... mon humour"] },
  { cat: "profond", q: "Ce dont tu es le plus reconnaissant(e) ?", o: ["Ma santé", "Mes proches", "Mon parcours", "Les petites choses"] },
  { cat: "profond", q: "Ce que tu dirais à ton toi de 15 ans ?", o: ["Détends-toi", "Fonce", "Prends soin de toi", "Tout ira bien"] },
  { cat: "profond", q: "Ce qui te fait te sentir le plus vivant(e) ?", o: ["L'aventure", "L'amour", "La création", "Le calme"] },

  /* ============== 🤔 PROBLÉMATIQUES DE COUPLE ============== */
  { cat: "couple", q: "Quand il y a une dispute, tu ?", o: ["J'en parle tout de suite", "J'ai besoin de calme d'abord", "Je fais la tête", "J'évite le conflit"] },
  { cat: "couple", q: "Ce qui t'agace le plus au quotidien ?", o: ["Le désordre", "Les retards", "Le manque d'écoute", "Le téléphone à table"] },
  { cat: "couple", q: "La gestion de l'argent dans le couple ?", o: ["Tout en commun", "Chacun sa part", "Un mix des deux", "On n'en parle pas assez"] },
  { cat: "couple", q: "Le ménage à la maison, pour toi ?", o: ["On partage 50/50", "Chacun ses tâches", "Je fais souvent plus", "Faut qu'on s'améliore"] },
  { cat: "couple", q: "Ce dont tu aimerais qu'on parle plus ?", o: ["Nos projets d'avenir", "Nos émotions", "Notre intimité", "Notre quotidien"] },
  { cat: "couple", q: "Ta vision des vacances idéales ?", o: ["Farniente à la plage", "Aventure & découverte", "City-trip culturel", "À la maison au calme"] },
  { cat: "couple", q: "On devrait passer plus de temps à ?", o: ["Sortir ensemble", "Cocooner", "Voir nos amis", "Faire des projets"] },
  { cat: "couple", q: "Pour les décisions importantes, tu es ?", o: ["Du genre à décider vite", "À peser le pour et le contre", "À demander conseil", "À suivre mon instinct"] },
  { cat: "couple", q: "Ce qui te rassure le plus dans le couple ?", o: ["La communication", "La fidélité", "Les projets communs", "Les petites attentions"] },
  { cat: "couple", q: "Vivre ensemble, ça veut dire surtout ?", o: ["Tout partager", "Garder son jardin secret", "S'équilibrer", "Évoluer ensemble"] },
  { cat: "couple", q: "Quand l'autre te déçoit, tu ?", o: ["Je le dis direct", "Je rumine un peu", "Je relativise", "Je me referme"] },
  { cat: "couple", q: "La belle-famille, pour toi ?", o: ["Très importante", "Importante avec des limites", "À gérer en diplomatie", "Source de stress parfois"] },
  { cat: "couple", q: "Le sujet qui fâche le plus chez nous ?", o: ["L'argent", "Le ménage", "La famille", "Les sorties / la jalousie"] },
  { cat: "couple", q: "Ta façon de gérer un désaccord ?", o: ["Le compromis", "Je cède souvent", "Je tiens bon", "On finit par en rire"] },
  { cat: "couple", q: "Le truc de l'autre qui te rend fou(folle) ?", o: ["Ses retards", "Son désordre", "Son téléphone", "Sa façon de conduire"] },
  { cat: "couple", q: "Quand on se dispute le soir, tu ?", o: ["On règle avant de dormir", "Je boude", "On dort fâchés", "Câlin de réconciliation obligatoire"] },
  { cat: "couple", q: "Ta vision des enfants ?", o: ["J'en veux / on en a", "Peut-être", "Pas pour l'instant", "Plutôt non"] },
  { cat: "couple", q: "La répartition des tâches chez nous ?", o: ["Bien équilibrée", "À revoir", "Je porte la maison", "On s'en sort pas mal"] },
  { cat: "couple", q: "Ce qui pourrait nous rapprocher encore ?", o: ["Plus de sorties", "Plus de discussions", "Plus d'intimité", "Plus de projets"] },
  { cat: "couple", q: "Ton besoin d'espace personnel ?", o: ["Beaucoup", "Un peu", "Très peu", "Zéro, je colle"] },
  { cat: "couple", q: "Quand l'autre est de mauvaise humeur, tu ?", o: ["Je console", "Je laisse passer", "Je m'éloigne", "Je dédramatise"] },
  { cat: "couple", q: "La place des amis dans ta vie ?", o: ["Essentielle", "Importante", "Le couple d'abord", "Ça dépend"] },
  { cat: "couple", q: "Pour les corvées, tu es plutôt ?", o: ["Je m'y mets direct", "Je procrastine", "Je négocie", "Je fais semblant d'oublier"] },
  { cat: "couple", q: "Ce qui te ferait le plus plaisir que l'autre fasse ?", o: ["Plus d'attentions", "Plus d'aide à la maison", "Plus de temps ensemble", "Plus de surprises"] },
  { cat: "couple", q: "Ta gestion de la jalousie ?", o: ["Pas un sujet", "Un peu mais ça va", "J'avoue être jaloux(se)", "On en parle ouvertement"] },
  { cat: "couple", q: "La communication chez nous ?", o: ["Excellente", "Bonne", "À améliorer", "On évite les sujets durs"] },
  { cat: "couple", q: "Ce que tu détestes faire seul(e) ?", o: ["Les courses", "Manger", "Dormir", "Regarder notre série sans l'autre"] },
  { cat: "couple", q: "Pour un projet commun, tu préfères ?", o: ["Voyager", "Acheter un logement", "Adopter un animal", "Monter un projet ensemble"] },
  { cat: "couple", q: "Quand l'autre a raison dans une dispute, tu ?", o: ["Je le reconnais", "Difficilement", "Jamais (rire)", "Je change de sujet"] },
  { cat: "couple", q: "Le rythme de vie idéal pour toi ?", o: ["Actif / sorties", "Tranquille / maison", "Un bon équilibre", "Au feeling"] },
  { cat: "couple", q: "Ce qui te ferait douter dans un couple ?", o: ["Le mensonge", "Le manque d'attention", "La routine", "La distance"] },
  { cat: "couple", q: "Pour gérer le stress du quotidien à deux ?", o: ["On en parle", "On se fait plaisir", "On s'organise mieux", "On respire un grand coup"] },
  { cat: "couple", q: "Ce que tu apprécies le plus que l'autre fasse pour toi ?", o: ["Cuisiner", "M'écouter", "Les petites attentions", "Me faire rire"] },
  { cat: "couple", q: "Ta réaction si l'autre oublie une date importante ?", o: ["Déçu(e) mais je comprends", "Vexé(e)", "Je fais la tête", "Aucun souci"] },
  { cat: "couple", q: "Le secret d'un couple qui dure, selon toi ?", o: ["La communication", "L'humour", "Le respect", "La complicité"] },
  { cat: "couple", q: "Pour les tâches que personne n'aime, tu ?", o: ["Je m'y colle", "On tire au sort", "On reporte", "J'attends que l'autre craque"] },
  { cat: "couple", q: "Ce que tu aimerais qu'on fasse plus souvent ?", o: ["Des dates", "Des câlins", "Des projets", "Rien, juste être ensemble"] },
  { cat: "couple", q: "Ta façon de dire pardon ?", o: ["Je le dis clairement", "Par un geste", "J'ai un peu de mal", "Avec de l'humour"] },
  { cat: "couple", q: "Le partage de la couette la nuit ?", o: ["On partage bien", "Je la vole", "On se la dispute", "Couettes séparées (la sagesse)"] },
  { cat: "couple", q: "Ce qui te rend le plus complice avec l'autre ?", o: ["Nos délires", "Nos silences", "Nos projets", "Notre quotidien"] },

  /* ============== 🌶️ COQUIN (mode optionnel) — sélection nettoyée, sans doublons ============== */
  /* -- Goûts & préférences -- */
  { cat: "coquin", q: "Ton moment préféré de l'intimité ?", o: ["Les préliminaires", "Le grand moment", "La tendresse d'après", "Les jeux de séduction"] },
  { cat: "coquin", q: "Ce qui te met le plus dans l'ambiance ?", o: ["Un massage", "Des mots coquins", "Une lumière tamisée", "Un regard complice"] },
  { cat: "coquin", q: "Ce qui te fait le plus craquer physiquement chez l'autre ?", o: ["Le regard", "La voix", "Les mains", "Le sourire"] },
  { cat: "coquin", q: "Ta zone sensible n°1 ?", o: ["Le cou", "Les oreilles", "Le bas du dos", "L'intérieur des cuisses"] },
  { cat: "coquin", q: "Ton style de baiser préféré ?", o: ["Doux et lent", "Passionné", "Volé par surprise", "Dans le cou"] },
  { cat: "coquin", q: "Ta tenue qui fait toujours de l'effet ?", o: ["Une chemise/chemisier ouvert", "De la lingerie", "Un jogging assumé", "Rien du tout"] },
  { cat: "coquin", q: "Le compliment coquin qui te fait fondre ?", o: ["Sur ton corps", "Sur ta façon de bouger", "Sur ton odeur", "Sur ton audace"] },
  { cat: "coquin", q: "Le mot le plus sexy à tes oreilles ?", o: ["Mon prénom murmuré", "Un compliment cru", "Viens là", "Je te veux"] },
  /* -- Habitudes & rythme -- */
  { cat: "coquin", q: "Tu préfères initier ou être surpris(e) ?", o: ["Initier", "Être surpris(e)", "Les deux", "Selon l'énergie"] },
  { cat: "coquin", q: "Ton signal pour dire 'j'ai envie' ?", o: ["Un message coquin", "Un geste tendre", "Un regard appuyé", "Je le dis franchement"] },
  { cat: "coquin", q: "Ton heure idéale pour un câlin coquin ?", o: ["Au réveil", "Sieste crapuleuse", "Le soir", "À l'improviste en journée"] },
  { cat: "coquin", q: "Ton rythme idéal dans la semaine ?", o: ["1 à 2 fois", "3 à 4 fois", "Tous les jours si possible", "Quand l'envie vient"] },
  { cat: "coquin", q: "Ton attitude juste après l'amour ?", o: ["Câlins obligatoires", "On discute", "Je m'endors direct", "Direction le frigo"] },
  { cat: "coquin", q: "Ce qui casse l'ambiance pour toi ?", o: ["Le téléphone", "La fatigue", "Le stress", "Une remarque maladroite"] },
  { cat: "coquin", q: "Ton plus grand turn-on inattendu ?", o: ["Une odeur", "Une voix", "Quelqu'un qui cuisine", "La confiance en soi"] },
  { cat: "coquin", q: "Ton plus gros turn-off ?", o: ["Le manque d'hygiène", "L'arrogance", "Le mauvais timing", "Le téléphone qui sonne"] },
  /* -- Audace & jeux -- */
  { cat: "coquin", q: "Le truc sexy que je fais sans m'en rendre compte ?", o: ["Ma façon de te regarder", "Quand je mordille ma lèvre", "Ma démarche", "Mon rire"] },
  { cat: "coquin", q: "Ton escapade coquine de rêve ?", o: ["Hôtel avec jacuzzi", "Cabane isolée", "Plage la nuit", "Notre lit, le classique imbattable"] },
  { cat: "coquin", q: "À quel point tu es joueur(se) au lit ?", o: ["Très, j'adore varier", "Plutôt joueur(se)", "Classique mais efficace", "Ça dépend de l'humeur"] },
  { cat: "coquin", q: "Le rôle qui te tente dans un petit jeu ?", o: ["Le/la dominant(e)", "Le/la timide", "L'inconnu(e) d'un soir", "Pas de rôle, juste nous"] },
  { cat: "coquin", q: "Le sextoy qui te tenterait ?", o: ["Aucun", "Un classique discret", "Un truc à deux", "Surprends-moi"] },
  { cat: "coquin", q: "Ton avis sur un grand miroir dans la chambre ?", o: ["Pour, j'adore", "Plutôt contre", "Pourquoi pas, on teste ?", "Ça me gêne un peu"] },
  { cat: "coquin", q: "À un strip-poker, tu finirais ?", o: ["Grand gagnant, habillé", "Je triche", "Je perds exprès", "Tout nu en 3 tours"] },
  { cat: "coquin", q: "Action ou Vérité, tu choisis quoi ?", o: ["Action toujours", "Vérité", "Ça dépend", "Les deux me font peur"] },
  { cat: "coquin", q: "Ta réaction à un message très osé en pleine journée ?", o: ["Je kiffe", "Je panique", "Je réponds pire", "Je coupe mon téléphone"] },
  { cat: "coquin", q: "Ce que tu trouves un peu surcoté ?", o: ["Les positions compliquées", "Les bougies partout", "Le champagne", "Les sextoys"] },
  { cat: "coquin", q: "Ta limite à ne jamais franchir ?", o: ["Rien en public", "Pas de tierce personne", "Pas de caméra", "J'ai presque pas de limite"] },

  /* ============== 🌶️ COQUIN — VÉRITÉS (questions corsées / un peu indiscrètes) ============== */
  { cat: "coquin", q: "Ta toute première fois, c'était plutôt ?", o: ["Magique", "Hyper gênante", "Drôle (catastrophe)", "On en reparlera jamais"] },
  { cat: "coquin", q: "Ton nombre de partenaires avant moi ?", o: ["1 à 2", "3 à 5", "6 à 10", "Mystère et boule de gomme"] },
  { cat: "coquin", q: "La personne que tu as le plus aimée avant moi ?", o: ["Un grand amour de jeunesse", "Une histoire courte mais intense", "Personne autant que toi", "Je préfère pas comparer"] },
  { cat: "coquin", q: "Ton fantasme le plus inavouable ?", o: ["Un jeu de rôle", "Un lieu interdit", "Un scénario à thème", "Je l'emporte dans ma tombe"] },
  { cat: "coquin", q: "Ce qu'on fait au lit que tu adores le plus ?", o: ["Les préliminaires qui durent", "Quand c'est spontané", "Les câlins d'après", "Tout, je suis fan"] },
  { cat: "coquin", q: "Ce qu'on fait que tu aimes le moins ?", o: ["Quand c'est trop rapide", "Quand le téléphone traîne", "Les positions acrobatiques", "Rien, c'est parfait"] },
  { cat: "coquin", q: "Ce que tu aimerais tester un jour ?", o: ["Un accessoire coquin", "Un lieu inattendu", "Un jeu de rôle", "Une petite vidéo souvenir"] },
  { cat: "coquin", q: "Le/la pote avec qui tu pourrais craquer (en théorie !) ?", o: ["Jamais, aucun(e)", "Hmm, peut-être", "Y'en a un(e) en tête", "Je plaide le 5e amendement"] },
  { cat: "coquin", q: "Ton plus grand secret, tu l'as déjà avoué à ?", o: ["Personne", "Mon/ma meilleur(e) ami(e)", "À toi", "Je garde tout pour moi"] },
  { cat: "coquin", q: "Le lieu le plus insolite où tu l'as déjà fait ?", o: ["En voiture", "En pleine nature", "Chez les parents (oups)", "Rien d'insolite... pour l'instant"] },
  { cat: "coquin", q: "Ton souvenir coquin préféré avec moi ?", o: ["Notre première fois", "Un week-end mémorable", "Un moment improvisé", "Top secret"] },

  /* ============== 😜 DÉCALÉ — SPÉCIAL ABSURDE / WTF ============== */
  { cat: "fun", q: "Si tu étais un fruit, tu serais ?", o: ["Une banane (assume)", "Une fraise", "Un piment", "Une noix de coco (dure dehors, tendre dedans)"] },
  { cat: "fun", q: "Le truc le plus bizarre que tu aies mangé ?", o: ["Des insectes", "Un truc périmé par flemme", "Un mélange chelou assumé", "Rien d'extrême"] },
  { cat: "fun", q: "Ta théorie du complot préférée (pour rire) ?", o: ["Les oiseaux sont des drones", "Les dinosaures existent encore", "La lune est un projecteur", "Aucune, je suis sérieux"] },
  { cat: "fun", q: "Si tu pouvais parler à un animal ?", o: ["Mon chat/chien", "Un dauphin", "Un pigeon (pour le clasher)", "Une mouette voleuse de frites"] },
  { cat: "fun", q: "Ton arme dans une apocalypse zombie ?", o: ["Une batte", "Un lance-flammes", "Mon charisme", "Je sers d'appât (RIP moi)"] },
  { cat: "fun", q: "Si tu étais un bruit, tu serais ?", o: ["Un cri de joie", "Un gros soupir", "Un rot discret", "Le bruit du frigo la nuit"] },
  { cat: "fun", q: "Ton talent inutile à sortir à un dîner ?", o: ["Plier ma langue", "Imiter un animal", "L'alphabet à l'envers", "Manger sans respirer"] },
  { cat: "fun", q: "Si la vie avait un bouton, lequel tu presses ?", o: ["Pause", "Avance rapide", "Retour arrière", "Aléatoire (le chaos)"] },
  { cat: "fun", q: "Le surnom ridicule qu'on t'a donné ?", o: ["Un truc de bébé", "Un truc lié à une boulette", "Un diminutif chelou", "J'en ai pas (menteur)"] },
  { cat: "fun", q: "Ton rêve absurde récurrent ?", o: ["Voler", "Perdre mes dents", "Être en retard à poil", "Manger sans fin"] },
  { cat: "fun", q: "Si tu devais vivre dans un genre de film ?", o: ["Une comédie", "Un film d'action", "Un Disney", "Un film d'horreur (au secours)"] },
  { cat: "fun", q: "Ce que tu fais quand personne ne regarde ?", o: ["Je danse", "Je me parle tout seul", "Je teste des grimaces", "Je mange direct dans le pot"] },
  { cat: "fun", q: "Ton super-vilain du quotidien ?", o: ["Le réveil", "Les pubs", "La sonnette quand je dors", "Le rouleau de PQ vide"] },
  { cat: "fun", q: "Si tu étais une appli du téléphone ?", o: ["Les réseaux sociaux", "La météo", "Le réveil", "Le jeu débile addictif"] },
  { cat: "fun", q: "Ce que tu ferais avec 24h d'invisibilité ?", o: ["Espionner mes potes", "Voyager gratos", "Faire des blagues", "Dormir tranquille"] },
  { cat: "fun", q: "Ton dernier repas sur Terre ?", o: ["Une raclette", "Sushis à volonté", "Un burger géant", "Que des desserts"] },
  { cat: "fun", q: "Si on te file un micro en soirée, tu ?", o: ["Je chante", "Je fais un discours", "Je le refile vite", "Je raconte une blague nulle"] },
  { cat: "fun", q: "Le défi débile que tu relèverais pour 100€ ?", o: ["Manger un truc dégueu", "Chanter dans la rue", "Rester muet 1h", "Aucun, j'ai ma dignité (un peu)"] },
  { cat: "fun", q: "Ta danse signature en soirée ?", o: ["Le robot", "Les bras en l'air", "Le déhanché discret", "Je squatte le buffet"] },
  { cat: "fun", q: "Si tu étais un mème internet ?", o: ["Le chat blasé", "Le mec qui transpire à choisir", "Le squelette qui attend", "Le chien dans la maison en feu"] },
  { cat: "fun", q: "Ton réflexe face à une porte marquée 'Tirez' ?", o: ["Je pousse à chaque fois", "Je lis bien avant", "Je fais comme si c'était voulu", "Je regarde si on m'a vu"] },
  { cat: "fun", q: "Le pire prénom que tu donnerais (pour rire) ?", o: ["Kevin", "Jean-Eudes", "Un prénom de fruit", "Le prénom de mon ex (jamais)"] },
  { cat: "fun", q: "Ta réaction si tu gagnais un concours de grimaces ?", o: ["Fier comme jamais", "Trop gêné", "Je remets le titre en jeu", "J'encadre le diplôme"] },
  { cat: "fun", q: "La chose la plus chère que tu casserais par maladresse ?", o: ["Un téléphone", "Un truc de luxe", "La voiture", "Mon orgueil"] },
  { cat: "fun", q: "Ton choix face à un selfie de groupe raté ?", o: ["On en refait 10", "Tant pis, on garde", "Je supprime en douce", "Je le mets en story exprès"] },

  /* ============== 🤔 PROBLÉMATIQUES — FAMILLE & ARGENT ============== */
  { cat: "couple", q: "Le sujet d'argent qui crée le plus de tension ?", o: ["Les dépenses imprévues", "L'épargne", "Qui paie quoi", "Les cadeaux à la famille"] },
  { cat: "couple", q: "Si on hérite d'une grosse somme, tu ?", o: ["On investit", "On profite à fond", "On épargne tout", "On aide la famille"] },
  { cat: "couple", q: "Si ta famille critique notre couple, tu ?", o: ["Je les recadre", "Je laisse couler", "Ça m'affecte", "Je prends ton parti à fond"] },
  { cat: "couple", q: "Pour les fêtes, tu préfères ?", o: ["Ma famille", "Ta famille", "Alterner équitablement", "Rester juste nous deux"] },
  { cat: "couple", q: "Le poste de dépense que tu couperais en premier ?", o: ["Les restos", "Les vacances", "Le shopping", "Les abonnements oubliés"] },
  { cat: "couple", q: "Si je dépense sans te prévenir, tu ?", o: ["Aucun souci si raisonnable", "Ça dépend du montant", "J'aimerais être prévenu(e)", "Ça me stresse"] },
  { cat: "couple", q: "Prêter de l'argent à un proche, pour toi ?", o: ["Oui sans souci", "Oui mais avec limites", "Plutôt non", "Jamais"] },
  { cat: "couple", q: "Le rêve qu'on devrait financer en priorité ?", o: ["Un voyage", "Un logement", "Un mariage / une fête", "Un projet perso"] },

  /* ============== 🧠 PERSO — VÉRITÉS ============== */
  { cat: "profond", q: "Ton objectif de vie n°1 ?", o: ["Être heureux", "Réussir professionnellement", "Fonder une famille", "Voyager / être libre"] },
  { cat: "profond", q: "Ta situation la plus gênante de ta vie ?", o: ["Une chute mémorable en public", "Un texto à la mauvaise personne", "Un trou de mémoire devant du monde", "J'ai tout refoulé"] },
  { cat: "profond", q: "Si tu pouvais effacer un moment de ta vie ?", o: ["Une grosse honte", "Une rupture", "Une bêtise de jeunesse", "Rien, tout m'a construit"] },
];

/* Rendu accessible aux autres scripts */
window.CATEGORIES = CATEGORIES;
window.QUESTIONS = QUESTIONS;
